Fix retry logic (2nd attempt)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -85,13 +85,13 @@ runs:
         max_attempts=5
         attempt=0
         while [[ $attempt -lt $max_attempts ]]; do
-            version_tag="$(curl --retry 5 -s -f https://api.github.com/repos/gitleaks/gitleaks/releases/latest | jq -r .name)"
+            version_tag="$(curl --retry 5 -s -f https://api.github.com/repos/gitleaks/gitleaks/releases/latest | jq -r .name || true)"
             version="${version_tag#v}"
             if [[ -n "$version" ]]; then
                 break
             fi
             attempt=$((attempt + 1))
-            echo "::warning::Attempt $attempt failed to fetch version, retrying in 60 seconds..." >&2
+            echo "::warning::Attempt $attempt failed to fetch version, retrying in 60 seconds. stdout: ${version_tag}" >&2
             sleep 60
         done
 
